version: '2'
services:
  redis:
    image: redis:4
    container_name: p2p_hlsaver_redis
  signaler:
    image: etng/p2p_hlsaver_signaler
    container_name: p2p_hlsaver_signaler
    ports:
      - 8181:8181
  tracker:
    image: etng/p2p_hlsaver_tracker
    command: ["/usr/local/bin/gotracker", "-redis_host", "redis:6379"]
    container_name: p2p_hlsaver_tracker
    ports:
      - 8787:8787
